### ISSUE TITLE
Parser breaks when using an `PropertyIsNull` Filter

### ISSUE THREAD

**Issue by weskamm** [terrestris/geostyler-sld-parser#10]
The parser currently breaks when feeding with an `PropertyIsNull` filter, as the following line 
https://github.com/terrestris/geostyler-sld-parser/blob/c2ac49b2a74a3876d3a2020a596939bef54153f9/src/SldStyleParser.ts#L156
tries to read a literal which does not exist in this case.

Should be fixed just by using

```
let value = null;
if (sldOperatorName !== 'PropertyIsNull') {
  value = sldFilter.Literal[0];
}
```

**Comment by KaiVolland** [comment]
Thanks for the issue and the fix allready.
