### ISSUE TITLE
Complex Polygons are not parsed correctly

### ISSUE THREAD

**Issue by amir-ba** [terrestris/geostyler-sld-parser#22]
Currently the `sld-parser` only parses the fill and stroke property of the polygons in a `sld` rule and doesn't  consider other `cssParameter`s such as `stroke-dasharray` or `GraphicFill`. In addition the parseer fails to consider multiple `PolygonSymbolizers`. 
[Example Sld](https://gist.github.com/amir-ba/a5558020403eeb94cd5953170252d34c) is a sample `sld` that the parser needs to be able to parse.

**Comment by chrismayer** [comment]
Closed due to https://github.com/terrestris/geostyler/issues/187.
